### ISSUE TITLE
Add `date` field to each version's release.

### ISSUE THREAD

**Issue by jbenet** [ipfs/distributions#61] opened 2016-04-08 02:35 UTC
- the index page shows a date. 
- it was hardcoded to `January 1, 2016`
- @whyrusleeping set it to `data.date` for the go-ipfs 0.4.0 release.
- @whyrusleeping added a `date` field _manually_ to `0.4.0` this time.
- other releases dont show dates.

TODO:
- [ ] add `date` to other old releases manually
- [ ] make sure `date` is generated automatically in the future

**Comment by lgierth** [comment] 2016-06-24 00:48
> add date to other old releases manually

I strongly disagree -- this would change the hashes of the release directories. Can I close this as a duplicate of #48?

**Comment by RichardLitt** [comment] 2016-06-24 12:06
SGTM, @lgierth

**Closed** 2016-07-03 02:46 UTC
